[package]
name = "ruut_functions"
version = "0.2.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[profile.bench]
debug = true

[[bench]]
name = "building_bench"
harness = false
debug = true

